# ./boot Source Files
BOOT_SRC  = boot/boot.c 
BOOT_SRC += boot/start.S

# ./common Source Files
COMMON_SRC  = common/common.c
COMMON_SRC += common/uart.c
COMMON_SRC += common/mmio.c

SRC_TARGETS = $(BOOT_SRC) $(COMMON_SRC)

export